[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style.toml"


[tool.poetry]
name = "wemake-python-package"
description = "Bleeding edge cookiecutter template to create new python packages"
version = "0.1.0"
readme = "README.md"
authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

license = "MIT"


[tool.poetry.dependencies]
python = "^3.7"

cookiecutter = "^2.1"
jinja2-git = "^1.1"
lice = "^0.6"


[tool.poetry.dev-dependencies]
binaryornot = "^0.4"

wemake-python-styleguide = "^0.16"
flake8-pytest-style = "^1.6"
nitpick = "^0.32"

pytest = "^7.1"
pytest-randomly = "^3.12"
pytest-cookies = "^0.6"

safety = "^1.10"
tomlkit = "^0.11"
