dist: xenial
language: python

python:
  - 3.6
  - 3.7

env:
  - POETRY_VERSION=1.0.3

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python
  - source "$HOME/.poetry/env"

install: poetry install
script: make test

after_success:
  # Send coverage to coveralls:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
